name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Commit
      uses: actions/checkout@v1

    - name: Cache Cargo
      uses: actions/cache@v1
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo
    
    - name: Cache binaryen
      uses: actions/cache@v1
      with:
        path: ~/binaryen
        key: ${{ runner.os }}-binaryen
    
    - name: Cache Target
      uses: actions/cache@v1
      with:
        path: livesplit-core/target
        key: ${{ runner.os }}-target

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: 'nightly'

    - name: Install Target
      run: rustup target add wasm32-unknown-unknown

    - name: Install Dependencies
      run: |
        set -e
        sh .github/workflows/install.sh
        source ~/.cargo/env || true
    
    - name: Build Application
      run: bash .github/workflows/build.sh
    
    - name: Deploy Application
      # if: startsWith(github.ref, 'refs/tags/')
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git checkout -b gh-pages
        mv dist/* .
        git add :/
        git commit -m "GitHub Pages build"
        git push --force https://action:${{ secrets.LIVESPLIT_ONE_DEPLOY }}@github.com/wooferzfg/LiveSplitOne.git
